# Neural Network For Classification

In [81]:
import pandas as pd
from textblob import TextBlob
import csv
df = pd.read_csv(r"L:\HP\Data Mining\TASA\Associated Modules\Set-3\tutorial\scrapped.csv")
news = df["text"].dropna()
ps = 0;tnew = 0.0;
paragraph,paragraphl = [],[]
ss = []
filep = open(r"L:\HP\Data Mining\TASA\Data\PParagraph.csv",'w')
filen = open(r"L:\HP\Data Mining\TASA\Data\NParagraph.csv",'w')
filene = open(r"L:\HP\Data Mining\TASA\Data\NEParagraph.csv",'w')
s = np.zeros(shape=(56,8))
i = 0; j = 0;
for new in news:
    #senval = []
    senew = TextBlob(new).sentences
    #print("Paragraph pol",parapol)
    count = 0
    for sen in senew:
        if(j > 7):
            break
        count = count + 1
        senpol = sen.sentiment.polarity
        s[i,j] = senpol
        j = j + 1
    #print(senval)
    #s = senval[1:7]    
    tnew = TextBlob(new).sentiment.polarity
    #print(tnew)
    if ( tnew > 0):
        #s = senval[1:7]
        ss.append(1)
        #filep.write(str(senval))
    elif (tnew < 0):
        #s = senval[1:7]
        ss.append(2)
        #filen.write(str(senval))
    elif(tnew == 0):
        #s = senval[1:7]
        ss.append(3)
        #filene.write(str(senval))
    j=0
    i = i + 1

In [82]:
filep.close()
filen.close()
filene.close()

In [7]:
mydict = dict()
mydict["one"] = paragraph
mydict["two"] = paragraphl

In [83]:
scipy.io.savemat("L:\HP\Data Mining\TASA\Data\p.mat",{'X':s,'Y':ss})

In [9]:
import scipy
import numpy as np

In [10]:
file.close()

In [41]:
len(ratios)

1249

In [54]:
def test(text):
    ttext = TextBlob(text)
    print(ttext)
    twords = ttext.words
    print(twords)
    return twords

In [154]:
aa = "121 Farmers owe the Maharashtra exchequer Rs 17,000 crore in the form of outstanding power bills for the agriculture pump sets, Chief Minister today told the Legislative Assembly. Mr Fadnavis also said though the government had initiated the process to recover the pending dues, it has stopped the drive temporarily taking into consideration various hardships being faced by the farmers." 

In [58]:
type(t)

textblob.blob.WordList

In [59]:
list(t)

['121',
 'Farmers',
 'owe',
 'the',
 'Maharashtra',
 'exchequer',
 'Rs',
 '17,000',
 'crore',
 'in',
 'the',
 'form',
 'of',
 'outstanding',
 'power',
 'bills',
 'for',
 'the',
 'agriculture',
 'pump',
 'sets',
 'Chief',
 'Minister',
 'today',
 'told',
 'the',
 'Legislative',
 'Assembly',
 'Mr',
 'Fadnavis',
 'also',
 'said',
 'though',
 'the',
 'government',
 'had',
 'initiated',
 'the',
 'process',
 'to',
 'recover',
 'the',
 'pending',
 'dues',
 'it',
 'has',
 'stopped',
 'the',
 'drive',
 'temporarily',
 'taking',
 'into',
 'consideration',
 'various',
 'hardships',
 'being',
 'faced',
 'by',
 'the',
 'farmers']

In [142]:
import os
pathp = r"""L:\HP\Data Mining\TASA\Bags\Data\Positive\ """
pathneg = r"""L:\HP\Data Mining\TASA\Bags\Data\Negative\ """
pathneu = r"""L:\HP\Data Mining\TASA\Bags\Data\Neutral\ """
ldp = os.listdir(pathp.strip())
ldneg = os.listdir(pathneg.strip())
ldneu = os.listdir(pathneu.strip())
                

In [63]:
ld

['neg-ant.txt',
 'neg.txt',
 'neg1.txt',
 'neg2.txt',
 'neg3.txt',
 'neu-syn.txt',
 'neu.txt',
 'neu_clean.txt',
 'pos.txt',
 'pos1.txt',
 'pos2.txt']

In [148]:
positive,negative,neutral = [],[],[]

In [149]:
for a in ldp:
    positive=(eval(open(str(pathp.strip()+a),'r').read()))
for b in ldneg:
    negative=(eval(open(str(pathneg.strip()+b),'r').read()))
for c in ldneu:
    neutral=(eval(open(str(pathneu.strip()+c),'r').read()))


In [129]:
a = ld[0]
file = open(str(path.strip()+a),'r')
b = eval(file.read())

In [131]:
file.close()

In [151]:
type(positive)

set

In [161]:
def test(text):
    pdepend=0.0;ndepend=0.0;nedepend = 0.0;
    pcount=0;ncount=0;necount=0;
    ttext = TextBlob(text)
    #print(ttext)
    twords = ttext.words
    #print(twords)
    for word in twords:
        if word in positive:
            pcount+=1
        elif word in negative:
            ncount+=1
        elif word in neutral:
            necount+=1
    tcount = pcount+ncount+necount
    pdepend = pcount/tcount
    ndepend = ncount/tcount
    nedepend = necount/tcount
    print(pdepend,ndepend,nedepend)
    return max(pdepend,ndepend,nedepend)

In [162]:
a = test(aa)

0.0 0.6666666666666666 0.3333333333333333


In [28]:
a = [1,2,3,4,5,6]
print(str(a))

[1, 2, 3, 4, 5, 6]


In [30]:
b = ''.join(str(a))

In [31]:
b


'[1, 2, 3, 4, 5, 6]'

In [36]:
b = " ".join(str(a))

In [67]:
a

[1, 2, 3, 4, 5, 6]

In [53]:
0 == 0.0


True

In [65]:
s = np.zeros(shape=(5,2))

In [56]:
s

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [59]:
s[1:2]

array([[ 0.,  0.]])

In [60]:
s[1:2] = 0.5236

In [61]:
s

array([[ 0.    ,  0.    ],
       [ 0.5236,  0.5236],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ]])

In [62]:
s[1:1]

array([], shape=(0, 2), dtype=float64)

In [63]:
s[1:1] = 0.2568


In [64]:
s

array([[ 0.    ,  0.    ],
       [ 0.5236,  0.5236],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ]])

In [66]:
s

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [69]:
s[0,1] = 2

In [70]:
s

array([[ 0.,  2.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [73]:
s = np.zeros(shape=(56,15))

In [75]:
s[0,7] = 0.2569

In [76]:
s

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.2569,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    , 